version: "2.1"
networks:
  k8s-ingress-explained:
    driver: bridge
services:
  frontend:
    image: "daggerok/k8s-ingress-explained-frontend:latest"
    ports: ["8004:8004"]
    environment:
      GREETING_HOST: "greeting-service"
      HELLO_HOST: "hello-variants-service"
    ulimits:
      memlock:
        hard: 2048
        soft: 1024
    networks: [k8s-ingress-explained]
  greeting-service:
    image: "daggerok/k8s-ingress-explained-greeting-service:latest"
    ports: ["8003:8003"]
    environment:
      HELLO_HOST: "hello-variants-service"
    ulimits:
      memlock:
        hard: 2048
        soft: 1024
    networks:
      k8s-ingress-explained:
        aliases:
          - greeting-service
  hello-variants-service:
    image: "daggerok/k8s-ingress-explained-hello-variants-service:latest"
    ports:
      - "8001:8001"
      - "8002:8002"
    ulimits:
      memlock:
        hard: 2048
        soft: 1024
    networks:
      k8s-ingress-explained:
        aliases:
          - hello-variants-service
#    healthcheck:
#      timeout: 1s
#      retries: 111
#      interval: 1s
#      #test: curl -f http://127.0.0.1:8001/actuator/health || exit 1
#      test: >
#        wget -q --spider http://hello-variants-service:8001/actuator/health || exit 1
